export const data = [
  {
    id: "1",
    url: "https://cdn2.thecatapi.com/images/32e.jpg",
    width: 500,
    height: 357,
    name: "Cat 1",
    price: 23,
  },
  {
    id: "2",
    url: "https://cdn2.thecatapi.com/images/aug.jpg",
    width: 480,
    height: 640,
    name: "Cat 2",
    price: 13,
  },
  {
    id: "3",
    url: "https://cdn2.thecatapi.com/images/chg.jpg",
    width: 620,
    height: 421,
    name: "Cat 3",
    price: 7,
  },
  {
    id: "4",
    url: "https://cdn2.thecatapi.com/images/e4g.gif",
    width: 400,
    height: 605,
    name: "Cat 4",
    price: 56,
  },
  {
    id: "5",
    url: "https://cdn2.thecatapi.com/images/MTUyNTA1OA.gif",
    width: 500,
    height: 281,
    name: "Cat 5",
    price: 34,
  },
  {
    id: "6",
    url: "https://cdn2.thecatapi.com/images/MTY3NjkyNQ.jpg",
    width: 640,
    height: 640,
    name: "Cat 6",
    price: 78,
  },
  {
    id: "7",
    url: "https://cdn2.thecatapi.com/images/MTczODA3NQ.jpg",
    width: 490,
    height: 737,
    name: "Cat 7",
    price: 11,
  },
  {
    id: "8",
    url: "https://cdn2.thecatapi.com/images/MjA4ODY5Ng.jpg",
    width: 598,
    height: 900,
    name: "Cat 8",
    price: 22,
  },
  {
    id: "9",
    url: "https://cdn2.thecatapi.com/images/Rx_gYvR2e.jpg",
    width: 970,
    height: 646,
    name: "Cat 9",
    price: 333,
  },
  {
    id: "10",
    url: "https://cdn2.thecatapi.com/images/FUJOW3SIi.jpg",
    width: 3060,
    height: 1722,
    name: "Cat 10",
    price: 222,
  },
];
